### PR TITLE
Login/Register pages

### PR DESCRIPTION
**Pull request by jdepree**
Separated out from Mike's generalist branch.

### CODE REVIEW

**Comment by malawi-mike** [comment]
i'll look for a good picture. i like the field of flowers but i agree that a group of people might be more inviting.

**Comment by malawi-mike** [comment]
img_1604-collage

something like this too busy?

**Comment by jdepree** [comment]
As a background, probably...  we could potentially have a solid color with
a couple tiles at random offsets.

**Comment by jdepree** [comment]
Supplying a z-index of -1 breaks these pages in some browsers - we'll have to find another way to achieve that effect.

**Pull request merged**
