### PR TITLE
adding sitemap

### PR DESCRIPTION
**Pull request by malawi-mike**

### CODE REVIEW

**Comment by jdepree** [comment]
I don't know much about sitemaps, but maybe tos/privacy_policy/faq should have lower priority so they're not presented to the user in search results?

**Comment by malawi-mike** [comment]
that's a good point but I don't think the prioritization matters much.

Screen Shot 2019-06-05 at 8 59 10 PM


https://www.searchenginejournal.com/xml-sitemap-best-practices/237649/#close

**Comment by jdepree** [comment]
Maybe we should leave those out then?

**Comment by jdepree** [comment]
*those pages

**Comment by malawi-mike** [comment]
maybe.  i included them because of this.  https://moz.com/blog/xml-sitemaps

Screen Shot 2019-06-05 at 9 30 34 PM

**Pull request merged**
