### PR TITLE
Making filters work correctly

### PR DESCRIPTION
**Pull request by jdepree**

### CODE REVIEW

**Comment by malawi-mike** [comment]
filters don't seem to interact, such that users can, for example, isolate all funded, education projects. would also be nice to display a message like "sorry, there are no projects matching that description."

**Comment by jdepree** [comment]
The problem with that is that the buttons do not show the current state of the filters.  In order to have overlapping filters, you would need to find a way to display the current state.

**Comment by malawi-mike** [comment]
isn't the lack of a displayed state a problem in general? are you saying that two filters is technically unfeasible or that it would be a bad user experience?

**Comment by jdepree** [comment]
Bad user experience.

**Comment by malawi-mike** [comment]
gotcha. yeah, we might just need to go with it. users can always back out with the "All" option. do you mind coding it? would love to give it a whirl.

**Pull request merged**
