### PR TITLE
Commit message

### PR DESCRIPTION
**Pull request by malawi-mike**

### CODE REVIEW

**Comment by jdepree** [comment]
I don't see any huge red flags.  Maybe just scan through and make sure you intended to make all the changes in there.  Change filenames to lowercase.

**Comment by malawi-mike** [comment]
Looks like some of the my changes are missing. Should I create a new branch and execute a new push?

**Comment by jdepree** [comment]
Where did they go?  Maybe just change those filenames, make a commit, push
it up, and we'll merge this one.

**Comment by malawi-mike** [comment]
ok, have a look. everything should be up there now.

**Comment by jdepree** [comment]
Not sure where all these new changes came from, but alright.

**Comment by malawi-mike** [comment]
yeah, super weird. those changes were made well before our conversation last night

**Pull request merged**
