### PR TITLE
Remove redundant meta

### PR DESCRIPTION
**Pull request by malawi-mike**

### CODE REVIEW

**Comment by jdepree** [comment]
Also, are there meta tags in project.php?  I believe I deliberately set that up to allow sharing of individual projects.  These meta-tags in header.inc will probably conflict with them.  Maybe we need to distribute the meta tags to all of the files that use header.inc instead?  Or put conditional meta tags in header.inc that show up if they haven't been previously provided?

**Comment by jdepree** [comment]
maybe you could put something like this before header.inc in project.php

$metaProvided = true;

then in header.inc:

if (isset($metaProvided) && $metaProvided) {
  // print meta tags
}

**Comment by malawi-mike** [comment]
sure thing. happy to do that now and push up those changes later this evening or over the weekend

**Comment by malawi-mike** [comment]
also, any chance you could put the full, current version of the site on 4and.me. saw that the home pages videos and a banner pic were removed

**Comment by jdepree** [comment]
updated

**Pull request merged**
