### PR TITLE
Adding stripe popup to donate buttons

### PR DESCRIPTION
**Pull request by jdepree**
We still need a way to specify the amount to donate.  We could have a dialog pop up before the stripe dialog (we might need to do this for name/address anyway?).  Or we could work a field into the card.

### CODE REVIEW

**Comment by malawi-mike** [comment]
here's some guidance on variable amounts at checkout: https://stripe.com/docs/recipes/variable-amount-checkout. it's unclear to me whether we can modify the card or need to create a new view. here's some more guidance: https://teamtreehouse.com/community/variable-amounts-with-stripe-and-php. this is what Watsi does, which makes it easier to add Paypal down the road.

screen shot 2017-08-24 at 5 28 09 pm

**Comment by jdepree** [comment]
We can popup a floater that shows something like this.  The materialize
modals (like the one I just added to the subscription button) should work.

**Comment by malawi-mike** [comment]
cool. we can also add a donation field to the donate button (ala Stripe), but a modal might work better. thoughts?

**Comment by jdepree** [comment]
Either is fine.

**Comment by malawi-mike** [comment]
i'll do some research on best practices for maximizing likelihood of giving and dollar amount donated

**Comment by malawi-mike** [comment]
we should definitely go with the modal. we can collect more info and allow folks to do stuff like dedicate the donation to another person.

**Comment by malawi-mike** [comment]
what do you think about a popup for the newsletter signup? they annoy the crap out of me. you?

**Comment by jdepree** [comment]
Yeah, definitely opposed to that

**Pull request merged**
